GameDevelopersForum/GameDevelopersForum/Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Models
{
	public class Message
	{
		public System.DateTime Time { get; set; }
		public string Text { get; set; }
		public int Id { get; set; }
		public Topic Topic { get; set; }
		public int? TopicId { get; set; }
		public User User { get; set; }
		public int? UserId { get; set; }
	}
}

GameDevelopersForum/GameDevelopersForum/Models/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Models
{
	public class News
	{
		public string Name { get; set; }
		public string PreviewImageName { get; set; }
		public string Description { get; set; }
		public DateTime PublishingDate { get; set; }
		public string Info { get; set; }
		public int Id { get; set; }
	}
}

GameDevelopersForum/GameDevelopersForum/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Models
{
	public class Topic
	{
        public int Id { get; set; }
        public string Name { get; set; }
		public string PreviewImageName { get; set; }
		public DateTime CreationDate { get; set; }
		public string Description { get; set; }
		public User User { get; set; }
		public int? UserId { get; set; }
		public List<Message> Messages { get; set; }

		public Topic()
		{
			Messages = new List<Message>();
		}
	}
}

GameDevelopersForum/GameDevelopersForum/Models/User.cs
using System;
using System.Collections.Generic;

namespace GameDevelopersForum.Models
{
	public class User
	{
		public int Id { get; set; }
		public string Login { get; set; }
		public string Email { get; set; }
		public string Password { get; set; }
		public string imageName { get; set; }
		public string About { get; set; }
		public DateTime RegistrationDate { get; set; }
        public List<Message> Messages { get; set; }
        public int? RoleId { get; set; }
        public Role Role { get; set; }

        public User()
		{
			Messages = new List<Message>();
		}
	}

	public class Role
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public List<User> Users { get; set; }
		public Role()
		{
			Users = new List<User>();
		}
	}
}

GameDevelopersForum/GameDevelopersForum/Controllers/DataBasesController.cs
using GameDevelopersForum.Models;
using GameDevelopersForum.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Controllers
{
	public class DataBasesController : Controller
	{
		private readonly ForumContext db;
        private readonly ILogger logger;

        public DataBasesController(ForumContext db, ILogger<DataBasesController> logger)
		{
			this.db = db;
            this.logger = logger;
		}

		[Authorize(Roles = "admin, moderator")]
		public IActionResult Index()
		{
			return View();
		}

		[Authorize(Roles = "admin, moderator")]
		public IActionResult News()
		{
			return View(db.News.ToList());
		}

		[Authorize(Roles = "admin")]
		public IActionResult Users()
		{
			return View(db.Users.ToList());
		}
		[Authorize(Roles = "admin, moderator")]
		public IActionResult Topics()
		{
			return View(db.Topics.ToList());
		}

        [Authorize(Roles = "admin, moderator")]
        public IActionResult Messages()
        {
            return View(db.Messages.ToList());
        }

        [HttpGet]
		public IActionResult TopicEdit(int Id)
		{
			Topic topic = db.Topics.Find(Id);
			if (User.IsInRole("admin") || User.IsInRole("moderator") || (User.Identity.IsAuthenticated && topic.Name == null))
			{
                ViewBag.CurrentTopic = topic;
				return View();
			}
			else
			{
                logger.LogWarning("Попытка входа обычным пользователем");
                return View(Content("Access denied"));
			}
		}

		[Authorize(Roles = "admin, moderator")]
		public IActionResult TopicDelete(int id)
		{
            List<Message> messages = db.Messages.Where(m => m.TopicId == id).ToList();
            foreach (var message in messages)
                db.Messages.Remove(message);
			db.Topics.Remove(db.Topics.Find(id));
			db.SaveChanges();
            logger.LogInformation($"Форум с id: {id} был успешно удалён");
            return RedirectToAction("Topics", "DataBases");
		}

		[Authorize(Roles = "admin, moderator")]
		public IActionResult NewsDelete(int id)
		{
			db.News.Remove(db.News.Find(id));
			db.SaveChanges();
            logger.LogInformation($"Новость с id: {id} была успешно удалена");
            return RedirectToAction("News", "DataBases");
		}

		[Authorize(Roles = "admin")]
		public IActionResult UserDelete(int id)
		{
			db.Users.Remove(db.Users.Find(id));
			db.SaveChanges();
            logger.LogInformation($"Пользователь с id: {id} была успешно удалён");
            return RedirectToAction("Users", "DataBases");
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult TopicEdit(TopicEditModel model, int id)
		{
			Topic topic = db.Topics.Find(id);
			
			if (ModelState.IsValid)
			{
				if (model.Description != null)
				{
					topic.Description = model.Description;
				}
				if (model.Name != null)
				{
					topic.Name = model.Name;
				}
				db.SaveChanges();
                logger.LogInformation($"Форум с id: {id} был успешно изменён");
                return RedirectToAction("List", "Forum");
			}
			ViewBag.CurrentTopic = topic;
            logger.LogInformation($"Форум с id: {id} не был успешно изменён: были введены некорректные данные");
            return View();
		}

		[HttpGet]
		[Authorize(Roles = "admin, moderator")]
		public IActionResult NewsEdit(int Id)
		{
			News news = db.News.Find(Id);
			ViewBag.CurrentNews = news;
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult NewsEdit(NewsEditModel model, int id)
		{
			News news = db.News.Find(id);

			if (ModelState.IsValid)
			{
				if (model.Description != null)
				{
					news.Description = model.Description;
				}
				if (model.Info != null)
				{
					news.Info = model.Info;
				}
				if (model.Name != null)
				{
					news.Name = model.Name;
				}
				db.SaveChanges();
                logger.LogInformation($"Новость с id: {id} была успешно изменена");
                return RedirectToAction("News", "DataBases");
			}
			ViewBag.CurrentTopic = news;
            logger.LogInformation($"Новость с id: {id} не была успешно изменена: были введены некорректные данные");
            return View();
		}

		public IActionResult UserAPI()
		{
			return View();
		}

		[HttpGet]
		[Authorize(Roles = "admin")]
		public IActionResult UserEdit(int Id)
		{
			User user = db.Users.Find(Id);
			ViewBag.CurrentUser = user;
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult UserEdit(UserEditModel model, int id)
		{
			User user = db.Users.Find(id);

			if (ModelState.IsValid)
			{
				if (model.Login != null)
				{
					user.Login = model.Login;
				}
				if (model.Email != null)
				{
					user.Email = model.Email;
				}
				if (model.About != null)
				{
					user.About = model.About;
				}
				if (model.Password != null)
				{
					user.Password = model.Password;
				}

				if (model.RoleId != null)
				{
					user.RoleId = model.RoleId;
				}
				db.SaveChanges();
                logger.LogInformation($"Пользователь с id: {id} был успешно изменён");
                return RedirectToAction("Users", "DataBases");
			}
			ViewBag.CurrentUser = user;
            logger.LogInformation($"Пользователь с id: {id} не был успешно изменён: были введены некорректные данные");
            return View();
		}

        [HttpGet]
        public IActionResult MessageEdit(int Id)
        {
            Message message = db.Messages.Find(Id);
            if (User.IsInRole("admin") || User.IsInRole("moderator") || (User.Identity.IsAuthenticated && message.Text == null))
            {
                ViewBag.CurrentMessage = message;
                return View();
            }
            else
            {
                logger.LogWarning("Попытка входа обычным пользователем");
                return View(Content("Access denied"));
            }
        }

        [Authorize(Roles = "admin, moderator")]
        public IActionResult MessageDelete(int id)
        {
            db.Messages.Remove(db.Messages.Find(id));
            db.SaveChanges();
            logger.LogInformation($"Сообщение с id: {id} было успешно удалено");
            return RedirectToAction("Messages", "DataBases");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult MessageEdit(MessagesEditModel model, int id)
        {
            Message message = db.Messages.Find(id);

            if (ModelState.IsValid)
            {
                if (model.Text != null)
                {
                    message.Text = model.Text;
                }
                db.SaveChanges();
                logger.LogInformation($"Сообщение с id: {id} было успешно изменено");
                return RedirectToAction("Messages", "DataBases");
            }
            ViewBag.CurrentMessage = message;
            logger.LogInformation($"Сообщение с id: {id} не было успешно изменено: были введены некорректные данные");
            return View();
        }
    }
}

GameDevelopersForum/GameDevelopersForum/Controllers/NewsController.cs
using GameDevelopersForum.Models;
using GameDevelopersForum.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Controllers
{
	public class NewsController : Controller
	{
		private readonly ForumContext db;
        private readonly ILogger logger;

        public NewsController(ForumContext db, ILogger<NewsController> logger)
		{
			this.db = db;
            this.logger = logger;
        }
		
		public IActionResult List()
		{
			List <News> news = db.News.OrderByDescending(x => x.PublishingDate).ToList<News>();
			return View(news);
		}

		[Authorize(Roles = "admin, moderator")]
		public IActionResult Create()
		{
			News news = new News { PublishingDate = DateTime.Now};

			db.News.Add(news);
			db.SaveChanges();

            logger.LogInformation("Запуск создания новости");
            return RedirectToAction("NewsEdit", new RouteValueDictionary(
	            new {
                    controller = "DataBases", action = "NewsEdit", Id = news.Id
                }));
		
		}
		public IActionResult Show(int id)
		{
			return View(db.News.Find(id));
		}
	}
}

GameDevelopersForum/GameDevelopersForum/Controllers/UsersController.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Controllers
{
	[Route("api/[controller]")]
	public class UsersController : Controller
	{
		ForumContext db;

        public UsersController(ForumContext db)
		{
			this.db = db;
		}

		[HttpGet]
		public IEnumerable<User> Get()
		{
			return db.Users.ToList();
		}


		[HttpGet("{id}")]
		public IActionResult Get(int id)
		{
			User user = db.Users.FirstOrDefault(x => x.Id == id);
			if (user == null)
				return NotFound();
			return new ObjectResult(user);
		}

		[HttpPost]
		public IActionResult Post([FromBody]User user)
		{
			if (user == null)
			{
                return BadRequest();
			}

			db.Users.Add(user);
			db.SaveChanges();
			return Ok(user);
		}

		[HttpPut]
		public IActionResult Put([FromBody]User user)
		{
			if (user == null)
			{
				return BadRequest();
			}
			if (!db.Users.Any(x => x.Id == user.Id))
			{
				return NotFound();
			}

			db.Update(user);
			db.SaveChanges();
			return Ok(user);
		}


		[HttpDelete("{id}")]
		public IActionResult Delete(int id)
		{
			User user = db.Users.FirstOrDefault(x => x.Id == id);
			if (user == null)
			{
				return NotFound();
			}
			db.Users.Remove(user);
			db.SaveChanges();
			return Ok(user);
		}

	}
}

GameDevelopersForum/GameDevelopersForum/ViewComponents/MessagesListViewComponent.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.ViewComponents
{
    [ViewComponent]
    public class MessagesListViewComponent : ViewComponent
    {
        private ForumContext db;
        public MessagesListViewComponent(ForumContext db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await db.Messages.ToListAsync());
        }
    }
}

GameDevelopersForum/GameDevelopersForum/ViewComponents/NewsListViewComponent.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.ViewComponents
{
	public class NewsListViewComponent : ViewComponent
	{
		private ForumContext db;
		public NewsListViewComponent(ForumContext db)
		{
			this.db = db;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View(await db.News.ToListAsync());
		}
	}
}

GameDevelopersForum/GameDevelopersForum/ViewComponents/TopicsListViewComponent.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.ViewComponents
{
	public class TopicsListViewComponent : ViewComponent
	{
		private ForumContext db;
		public TopicsListViewComponent(ForumContext db)
		{
			this.db = db;
		}

		public async Task <IViewComponentResult> InvokeAsync()
		{
			return View(await db.Topics.ToListAsync());
		}
	}
}

GameDevelopersForum/GameDevelopersForum/ViewComponents/UsersListViewComponent.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.ViewComponents
{
	public class UsersListViewComponent : ViewComponent
	{
		private ForumContext db;
		public UsersListViewComponent(ForumContext db)
		{
			this.db = db;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View(await db.Users.ToListAsync());
		}
	}
}

GameDevelopersForum/GameDevelopersForum/Views/DataBases/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<div style="width:50%; margin: auto auto auto auto;">
    <a class="btn btn-lg btn-primary btn-block img-rounded" asp-controller="DataBases" asp-action="Messages">
        @Localizer["message"]
    </a>
    <a class="btn btn-lg btn-primary btn-block img-rounded" asp-controller="DataBases" asp-action="News">
        @Localizer["news"]
    </a>
    <a class="btn btn-lg btn-primary btn-block img-rounded" asp-controller="DataBases" asp-action="Topics">
        @Localizer["forum"]
    </a>
    @if (User.IsInRole("admin"))
    {
        <a class="btn btn-lg btn-primary btn-block img-rounded" type="submit" asp-controller="DataBases" asp-action="Users">
            @Localizer["users"]
        </a>
    }
</div>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/MessageEdit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model GameDevelopersForum.ViewModels.MessagesEditModel
<form asp-action="MessageEdit" asp-controller="DataBases" asp-anti-forgery="true" class="text-center;" style="margin: auto auto auto auto; max-width: 30%; transform: translateY(55px)">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div>
            <input style="width:100%" class="img-rounded" asp-for="Text" placeholder="@Localizer["name"]: @ViewBag.CurrentMessage.Text" />
            <span asp-validation-for="Text" />
        </div>
        <br/>
        <div>
            <input type="submit" value="@Localizer["save_changes"]" class="btn btn-lg btn-primary btn-block img-rounded" />
        </div>
    </div>
</form>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/Messages.cshtml
<div style="width:100%; background-color:white">
    @await Component.InvokeAsync("MessagesList")
</div>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/News.cshtml
<div style="width:100%; background-color:white">
    @await Component.InvokeAsync("NewsList")
</div>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/NewsEdit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model GameDevelopersForum.ViewModels.NewsEditModel
<form asp-action="NewsEdit" asp-controller="DataBases" asp-anti-forgery="true" class="text-center;" style="margin: auto auto auto auto; max-width: 30%; transform: translateY(55px)">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div>
            <input style="width:100%" class="img-rounded" asp-for="Name" placeholder="@Localizer["name"]: @ViewBag.CurrentNews.Name" />
            <span asp-validation-for="Name" />
        </div>
        <br />
        <div>
            <textarea style="width:100%" class="img-rounded" asp-for="Description" placeholder="@Localizer["description"]: @ViewBag.CurrentNews.Description"></textarea><br />
            <span asp-validation-for="Description" />
        </div>
        <div>
            <textarea style="width:100%" class="img-rounded" asp-for="Info" placeholder="@Localizer["info"]: @ViewBag.CurrentNews.Info"></textarea><br />
            <span asp-validation-for="Info" />
        </div>
        <div>
            <input type="submit" value="@Localizer["save_changes"]" class="btn btn-lg btn-primary btn-block img-rounded" />
        </div>
    </div>
</form>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/TopicEdit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model GameDevelopersForum.ViewModels.TopicEditModel
<form asp-action="TopicEdit" asp-controller="DataBases" asp-anti-forgery="true" class="text-center;" style="margin: auto auto auto auto; max-width: 30%; transform: translateY(55px)">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div>
            <input style="width:100%" class="img-rounded" asp-for="Name" placeholder="@Localizer["name"]: @ViewBag.CurrentTopic.Name" />
            <span asp-validation-for="Name" />
        </div>
        <br />
        <div>
            <textarea style="width:100%" class="img-rounded" asp-for="Description" placeholder="@Localizer["description"]: @ViewBag.CurrentTopic.Description"></textarea><br />
            <span asp-validation-for="Description" />
        </div>
        <div>
            <input type="submit" value="@Localizer["save_changes"]" class="btn btn-lg btn-primary btn-block img-rounded" />
        </div>
    </div>
</form>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/Topics.cshtml
<div style="width:100%; background-color:white">
    @await Component.InvokeAsync("TopicsList")
</div>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/UserAPI.cshtml
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

<div style="background-color:brown">

    <h2>Список пользователей</h2>
    <form name="userForm">
        <input type="hidden" name="Id" value="0" />
        <div class="form-group">
            <label for="Login">Логин:</label>
            <input class="form-control" name="Login" />
        </div>

        <div class="form-group">
            <label for="Email">Email:</label>
            <input class="form-control" name="Email" />
        </div>
        <div class="form-group">
            <label for="Password">Пароль:</label>
            <input class="form-control" name="Password" />
        </div>
        <div class="form-group">
            <label for="About">О себе:</label>
            <input class="form-control" name="About" />
        </div>

        <div class="panel-body">
            <button type="submit" class="btn btn-sm btn-primary">Сохранить</button>
            <a id="reset" class="btn btn-sm btn-primary">Сбросить</a>
        </div>
    </form>
    <table class="table table-condensed table-striped table-bordered">
        <thead><tr><th>Id</th><th>Логин</th><th>О себе</th><th>Пароль</th> <th>Email</th><th></th></tr></thead>
        <tbody>
        </tbody>
    </table>
</div>
<script>
    // Получение всех пользователей
    function GetUsers() {
        $.ajax({
            url: '/api/users/',
            type: 'GET',
            contentType: "application/json",
            success: function (users) {
                var rows = "";
                $.each(users, function (index, user) {
                    // добавляем полученные элементы в таблицу
                    rows += row(user);
                })
                $("table tbody").append(rows);
            }
        });
    }
    // Получение одного пользователя
    function GetUser(Id) {
        $.ajax({
            url: '/api/users/' + Id,
            type: 'GET',
            contentType: "application/json",
            success: function (user) {
                var form = document.forms["userForm"];
                form.elements["Id"].value = user.Id;
                form.elements["Login"].value = user.Login;
                form.elements["About"].value = user.About;
                form.elements["Password"].value = user.Password;
                form.elements["Email"].value = user.Email;
            }
        });
    }
    // Добавление пользователя
    function CreateUser(userLogin, userAbout, userPassword, userEmail) {
        $.ajax({
            url: "api/users",
            contentType: "application/json",
            method: "POST",
            data: JSON.stringify({
                Login: userLogin,
                About: userAbout,
                Password: userPassword,
                Email: userEmail
            }),
            success: function (user) {
                reset();
                $("table tbody").append(row(user));
            }
        })
    }
    // Изменение пользователя
    function EditUser(userId, userLogin, userAbout, userPassword, userEmail) {
        $.ajax({
            url: "api/users",
            contentType: "application/json",
            method: "PUT",
            data: JSON.stringify({
                Id: userId,
                Login: userLogin,
                About: userAbout,
                Password: userPassword,
                Email: userEmail
            }),
            success: function (user) {
                reset();
                $("tr[data-rowid='" + user.Id + "']").replaceWith(row(user));
            }
        })
    }

    // сброс формы
    function reset() {
        var form = document.forms["userForm"];
        form.reset();
        form.elements["Id"].value = 0;
    }

    // Удаление пользователя
    function DeleteUser(Id) {
        $.ajax({
            url: "api/users/" + Id,
            contentType: "application/json",
            method: "DELETE",
            success: function (user) {
                $("tr[data-rowid='" + user.Id + "']").remove();
            }
        })
    }
    // создание строки для таблицы
    var row = function (user) {
        return "<tr data-rowid='" + user.Id + "'><td>" + user.Id + "</td>" +
            "<td>" + user.Login + "</td> <td>" +
            user.About + "</td> <td>" +
            user.Password + "</td> <td>" + user.Email + "</td>" +
        "<td><a class='editLink' data-Id='" + user.Id + "'>Изменить</a> | " +
            "<a class='removeLink' data-Id='" + user.Id + "'>Удалить</a></td></tr>";
    }
    // сброс значений формы
    $("#reset").click(function (e) {

        e.preventDefault();
        reset();
    })

    // отправка формы
    $("form").submit(function (e) {
        e.preventDefault();
        var Id = this.elements["Id"].value;
        var Login = this.elements["Login"].value;
        var About = this.elements["About"].value;
        var Password = this.elements["Password"].value;
        var Email = this.elements["Email"].value;
        if (Id == 0)
            CreateUser(Login, About, Password, Email);
        else
            EditUser(Id, Login, About, Password, Email);
    });

    // нажимаем на ссылку Изменить
    $("body").on("click", ".editLink", function () {
        var Id = $(this).data("Id");
        GetUser(Id);
    })
    // нажимаем на ссылку Удалить
    $("body").on("click", ".removeLink", function () {
        var Id = $(this).data("Id");
        DeleteUser(Id);
    })

    // загрузка пользователей
    GetUsers();

</script>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/UserEdit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model GameDevelopersForum.ViewModels.UserEditModel
<form asp-action="UserEdit" asp-controller="DataBases" asp-anti-forgery="true" class="text-center;" style="margin: auto auto auto auto; max-width: 30%; transform: translateY(55px)">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div>
            <input style="width:100%" class="img-rounded" asp-for="Login" placeholder="@Localizer["login"]: @ViewBag.CurrentUser.Login" />
            <span asp-validation-for="Login" />
        </div>
        <br />
        <div>
            <input style="width:100%" class="img-rounded" asp-for="Email" placeholder="e-mail: @ViewBag.CurrentUser.Email" />
            <span asp-validation-for="Email" />
        </div>
        <br />
        <div>
            <textarea style="width:100%" class="img-rounded" asp-for="About" placeholder="@Localizer["about"]: @ViewBag.CurrentUser.About"></textarea><br />
            <span asp-validation-for="About" />
        </div>
        <div>
            <input style="width:100%" class="img-rounded" asp-for="Password" placeholder="@Localizer["password"]: @ViewBag.CurrentUser.Password" />
            <span asp-validation-for="Password" />
        </div>
        <div>
            <input style="width:100%" class="img-rounded" asp-for="RoleId" placeholder="RoleId: @ViewBag.CurrentUser.RoleId" />
            <span asp-validation-for="RoleId" />
        </div>
        <div>
            <input type="submit" value="@Localizer["save_changes"]" class="btn btn-lg btn-primary btn-block img-rounded" />
        </div>
    </div>
</form>

GameDevelopersForum/GameDevelopersForum/Views/DataBases/Users.cshtml
<div style="width:100%; background-color:white">
    @await Component.InvokeAsync("UsersList")
    </div>