GameDevelopersForum/GameDevelopersForum/Controllers/ChatController.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Controllers
{
	public class ChatController : Controller
	{
		private readonly ForumContext db;

        public ChatController(ForumContext db)
		{
            this.db = db;
		}
		
		public IActionResult Chat()
		{
            List<Message> messages = db.Messages.Where(u => u.TopicId == null).OrderByDescending(x => x.Time).Take(100).ToList();
			List<string> Users = new List<string>();  
			foreach (var message in messages)
			{
				if (message.UserId != null) {
					Users.Add(db.Users.Find(message.UserId).Login);
                }
				else
				{
					Users.Add("Anonymus");
				}
			}
			ViewBag.Users = Users;
			
			return View(messages);
		}


	}
}

GameDevelopersForum/GameDevelopersForum/Controllers/ForumController.cs
using GameDevelopersForum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Controllers
{
	public class ForumController : Controller
	{
		private readonly ForumContext db;
        private readonly ILogger logger;

        public ForumController(ForumContext db, ILogger<ForumController> logger)
		{
            this.logger = logger;
			this.db = db;
		}

		[Authorize]
		public IActionResult Create()
		{
			Topic topic = new Topic
			{
				CreationDate = DateTime.Now,
				User = db.Users.FirstOrDefault(u => u.Login == User.Identity.Name),
			};

			db.Topics.Add(topic);
			db.SaveChanges();

            logger.LogInformation("Запуск создания форума");
            return RedirectToAction("TopicEdit", new RouteValueDictionary(new
            {
                controller = "DataBases", action = "TopicEdit", Id = topic.Id
            }));

		}

		public IActionResult List()
		{
			return View(db.Topics.Take(countTopicsToShow).ToList());
		}

        [HttpPost]
        public async Task<IActionResult> Send(int id, string text)
        {
            try
            {
                User user = db.Users.First(u => u.Login == User.Identity.Name);
                Topic topic = db.Topics.Find(id);
                Message message = new Message { Text = text, User = user, Time = DateTime.Now, Topic = topic };
                db.Messages.Add(message);
                await db.SaveChangesAsync();
                logger.LogInformation($"Пользователь с id: {user.Id} написал текст: '{text}' для форума с id: {id}");
                return RedirectToAction($"/{id}", "/forum");
            }

            catch
            {
                logger.LogInformation($"Пользователь, не вошедший в систему, пытался написать текст: '{text}' для форума с id: {id}");
                return BadRequest("Дубина, ты ж не зарегался!");
            }
        }

        public IActionResult Show(int id)
        {
            Topic topic = db.Topics.Find(id);
            ViewBag.User = db.Users.Find(topic.UserId);
            IQueryable<Message> messages = db.Messages.Where(m => m.TopicId == id);
            foreach (var message in messages)
            {
                User user = db.Users.Where(u => u.Id == message.UserId).First();
                message.User = user;
            }
            ViewBag.Messages = messages;
            return View(topic);
        }

        [HttpGet]
		public async Task<IActionResult> TopicList(int pageNumber = 0)
		{
			if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
			{
				return PartialView("~/Views/Forum/ListGet.cshtml", await GetTopicList(pageNumber));
			}
			else return View(await GetTopicList(pageNumber));
		}

		const int countTopicsToShow = 5;

        private async Task<List<Topic>> GetTopicList(int pageNumber)
        {
            var topics = db.Topics;

            return topics.Skip(pageNumber * countTopicsToShow).Take(countTopicsToShow).ToList();
        }
    }
}

GameDevelopersForum/GameDevelopersForum/Controllers/NewsController.cs
using GameDevelopersForum.Models;
using GameDevelopersForum.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameDevelopersForum.Controllers
{
	public class NewsController : Controller
	{
		private readonly ForumContext db;
        private readonly ILogger logger;

        public NewsController(ForumContext db, ILogger<NewsController> logger)
		{
			this.db = db;
            this.logger = logger;
        }
		
		public IActionResult List()
		{
			List <News> news = db.News.OrderByDescending(x => x.PublishingDate).ToList<News>();
			return View(news);
		}

		[Authorize(Roles = "admin, moderator")]
		public IActionResult Create()
		{
			News news = new News { PublishingDate = DateTime.Now};

			db.News.Add(news);
			db.SaveChanges();

            logger.LogInformation("Запуск создания новости");
            return RedirectToAction("NewsEdit", new RouteValueDictionary(
	            new {
                    controller = "DataBases", action = "NewsEdit", Id = news.Id
                }));
		
		}
		public IActionResult Show(int id)
		{
			return View(db.News.Find(id));
		}
	}
}

GameDevelopersForum/GameDevelopersForum/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameDevelopersForum</title>

    <link href="https://fonts.googleapis.com/css?family=Vibur" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="~/css/neon_text.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <div id="container">
        <nav class="navbar navbar-inverse navbar-fixed-top">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    @*<span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>*@
                </button>

                <a asp-controller="Home" asp-action="Index" class="navbar-brand sign__word">OVERGAME</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>
                        <a asp-controller="News" asp-action="List">
                            @Localizer["news"]
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Forum" asp-action="List">
                            @Localizer["forum"]
                        </a>
                    </li>
                    @if (User.IsInRole("admin") || User.IsInRole("moderator"))
                    {
                        <li>
                            <a asp-controller="DataBases" asp-action="Index">
                                @Localizer["database"]
                            </a>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Account" asp-action="Profile">@User.Identity.Name</a></li>
                        <li>
                            <a asp-controller="Account" asp-action="Logout">
                                @Localizer["logout"]
                            </a>
                        </li>
                        <li><a asp-controller="Chat" asp-action="Chat">@Localizer["chat"]</a></li>
                    }
                    else
                    {
                        <li>
                            <a asp-controller="Account" asp-action="Register">
                                @Localizer["register"]
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Account" asp-action="Login">
                                @Localizer["signin"]
                            </a>
                        </li>

                    }
                    <li>
                        @await Html.PartialAsync("_SelectLanguagePartial")
                    </li>

                </ul>
    </div>
</nav>

<partial name="_CookieConsentPartial" />
<div id="particles-js"> </div>
<div id="page-wrapper">

    @RenderBody()

    @*<footer>
            <p>&copy; 2019 - OVERGAME</p>
        </footer>*@

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js"></script>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)

</div>
</body>
</html>

GameDevelopersForum/GameDevelopersForum/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:15px; "
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    <a style="color:#868686">@Localizer["Language:"]</a> <select style="background-color: #222222; text-decoration-color:#868686; color:#868686" name="culture" onchange="this.form.submit();"
                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                    asp-items="cultureItems"></select>
</form>